# Generated by Django 3.1.6 on 2021-03-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=30)),
                ('first', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='directors/')),
            ],
            options={
                'ordering': ['last', 'first'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imdb.director')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
