# Generated by Django 3.1.6 on 2021-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_movie_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
