# Generated by Django 3.1.6 on 2021-04-02 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_auto_20210402_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='plots/'),
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.movie')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
